name: Hello World
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: touch /tmp/{a..z}.txt
        shell: bash
      - name: Modify permission
        run: sudo chmod -R 777 /tmp/
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: text files
          path: /tmp/
